Repository NordicSemiconductor/IOS-nRF-Connect-Device-Manager, pull requests merged in 2025-08, with the labels that each got.

#362 Attempted Support for Group-Specific Errors in FileSystemManager
  Source/Managers/FileSystemManager.swift
Labels: documentation, enhancement, good first issue

#363 Added casting for specific FileSystemManagerError
  Source/Managers/FileSystemManager.swift
Labels: bug, documentation

#364 Added McuMgrParameters step to FileSystemManager
  Source/Managers/FileSystemManager.swift
Labels: bug, enhancement

#370 Cleanup of LogStatsController
  Example/Example/View Controllers/Manager/LogsStatsController.swift
Labels: documentation

#373 Preliminary (as in, we'd be surprised if there are no issues) support for Pipelining in FileSystemManager
  Example/Example/View Controllers/Manager/FileUploadViewController.swift
  Source/Managers/FileSystemManager.swift
  Source/Managers/ImageManager.swift
Labels: documentation, enhancement

#377 File Download Reassembly Correction
  README.md
Labels: documentation

#378 Fix: Report missing upload configuration when using legacy upload(name:data:offset:callback:) API directly instead of crashing
  Source/Managers/FileSystemManager.swift
Labels: bug, documentation

#382 Dynamic bluetooth UUIDs
  Example/Example/View Controllers/Manager/BaseViewController.swift
  Example/Example/View Controllers/Scanner/ScannerViewController.swift
  Source/Bluetooth/McuMgrBleTransport+CBCentralManagerDelegate.swift
  Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
  Source/Bluetooth/McuMgrBleTransport.swift
  Source/Bluetooth/UuidConfig.swift
Labels: enhancement

#384 Cleanup of McuMgrBleTransport Configuration API
  Example/Example/View Controllers/Manager/BaseViewController.swift
  Example/Example/View Controllers/Scanner/ScannerViewController.swift
  Source/Bluetooth/McuMgrBleTransport+CBCentralManagerDelegate.swift
  Source/Bluetooth/McuMgrBleTransport+CBPeripheralDelegate.swift
  Source/Bluetooth/McuMgrBleTransport.swift
  Source/Bluetooth/McuMgrBleTransportConfguration.swift
  Source/Bluetooth/UuidConfig.swift
Labels: documentation

#387 Initial NCS Bare Metal Firmware Update Support
  README.md
  Source/Managers/DFU/FirmwareUpgradeManager.swift
  Source/McuMgrResponse.swift
Labels: documentation, enhancement

#388 Report Invalid Bootloader Mode Error for Bare Metal Firmware
  Source/Managers/DFU/FirmwareUpgradeManager.swift
Labels: documentation

#390 Fix: McuMgrBleTransport now checks if current MTU is valid after Connection (Result)Lock
  Source/Bluetooth/McuMgrBleTransport.swift
  Source/Managers/DFU/FirmwareUpgradeManager.swift
Labels: bug, documentation, enhancement

#391 Deleted Unnecessary SMP_SVR_BT_L2CAP_MTU Constant
  Source/Managers/FileSystemManager.swift
Labels: bug, enhancement
